[book]
authors = ["Anirban Basu"]
language = "en"
text-direction = "ltr"
multilingual = false
src = "src"
title = "{ch@tty cod:r} documentation"
description = "The **chatty-coder** is an agent-based human-in-the-loop computer program code generator."

[rust]
edition = "2018"

[build]
build-dir = "book"
create-missing = false

[preprocessor.index]

[preprocessor.links]

[output.html]
default-theme = "light"
smart-punctuation = true
mathjax-support = true
copy-fonts = true
additional-css = []
additional-js = []
no-section-label = false
git-repository-url = "https://github.com/anirbanbasu/chatty-coder"
git-repository-icon = "fa-github"
site-url = "/"

[output.html.fold]
enable = false    # whether or not to enable section folding
level = 0         # the depth to start folding


[output.html.search]
enable = true            # enables the search feature
limit-results = 30       # maximum number of search results
teaser-word-count = 30   # number of words used for a search result teaser
use-boolean-and = true   # multiple search terms must all match
boost-title = 2          # ranking boost factor for matches in headers
boost-hierarchy = 1      # ranking boost factor for matches in page names
boost-paragraph = 1      # ranking boost factor for matches in text
expand = true            # partial words will match longer terms
heading-split-level = 3  # link results to heading levels
copy-js = false           # include Javascript code for search

[output.html.print]
enable = true    # include support for printable output
page-break = true # insert page-break after each chapter
